"""Helpers for thin main graph."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict

from kardcraft.db.card_repository import CardRepository
from kardcraft.db.postgres import postgres
from kardcraft.services.pack_workspace import WorkspaceCard, pack_workspace
from kardcraft.workflow.graphs.main_graph.state import MainState


def canonical_user_input(state: MainState) -> str:
    value = str(state.get("user_input") or "").strip()
    if value:
        return value
    return str(state.get("topic") or "").strip()


def map_intent_input(state: MainState) -> Dict[str, Any]:
    return {
        "user_input": canonical_user_input(state),
        "file_ids": state.get("file_ids", []),
        "metadata": {
            "target_count": state.get("target_count", 10),
            "difficulty_level": state.get("difficulty_level", "medium"),
        },
    }


async def save_cards_to_workspace(cards: list, workspace_id: str, owner: str) -> list:
    """Persist cards to PostgreSQL and mirror them into pack workspace."""
    if not cards:
        return []

    session_id = str(workspace_id or "").strip()
    if not session_id:
        return []

    saved_card_ids: list[str] = []

    if not postgres._initialized:
        await postgres.initialize()

    try:
        existing_pack = await pack_workspace.get_workspace(session_id)
        if not existing_pack:
            await pack_workspace.create_workspace(session_id)
    except Exception:
        pass

    now = datetime.utcnow().isoformat()
    pack_cards: list[WorkspaceCard] = []

    async with postgres.session() as session:
        repo = CardRepository(session)
        for index, card in enumerate(cards):
            if not isinstance(card, dict):
                continue
            front = str(card.get("front") or "").strip()
            back = str(card.get("back") or "").strip()
            if not front or not back:
                continue

            content_data = {
                "front": front,
                "back": back,
                "tags": card.get("tags", []) or [],
                "concepts": card.get("concepts", []) or [],
            }

            try:
                created = await repo.create_card(
                    owner,
                    str(card.get("model") or "default"),
                    content_data,
                    content_data.get("concepts", []),
                    "Generated by AI",
                )
                card_id = created.card_id
                saved_card_ids.append(card_id)

                pack_cards.append(
                    WorkspaceCard(
                        temp_id=str(card.get("id") or card_id),
                        order=int(card.get("order", index)),
                        model=str(card.get("model") or "default"),
                        content=content_data,
                        media=card.get("media", []) or [],
                        version=1,
                        modified_at=now,
                        status=str(card.get("status") or "draft"),
                        source_doc=card.get("source_doc"),
                        source_range=card.get("source_range"),
                    )
                )
            except Exception:
                continue

    if pack_cards:
        try:
            await pack_workspace.add_cards(session_id, pack_cards, source="ai")
        except Exception:
            pass

    return saved_card_ids
