# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import file_storage_pb2 as file__storage__pb2


class FileStorageServiceStub(object):
    """FileStorageService provides file storage operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.stream_unary(
                '/file_storage.FileStorageService/Upload',
                request_serializer=file__storage__pb2.UploadRequest.SerializeToString,
                response_deserializer=file__storage__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.Download = channel.unary_stream(
                '/file_storage.FileStorageService/Download',
                request_serializer=file__storage__pb2.DownloadRequest.SerializeToString,
                response_deserializer=file__storage__pb2.DownloadResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/file_storage.FileStorageService/Delete',
                request_serializer=file__storage__pb2.DeleteRequest.SerializeToString,
                response_deserializer=file__storage__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Exists = channel.unary_unary(
                '/file_storage.FileStorageService/Exists',
                request_serializer=file__storage__pb2.ExistsRequest.SerializeToString,
                response_deserializer=file__storage__pb2.ExistsResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/file_storage.FileStorageService/List',
                request_serializer=file__storage__pb2.ListRequest.SerializeToString,
                response_deserializer=file__storage__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetMetadata = channel.unary_unary(
                '/file_storage.FileStorageService/GetMetadata',
                request_serializer=file__storage__pb2.GetMetadataRequest.SerializeToString,
                response_deserializer=file__storage__pb2.GetMetadataResponse.FromString,
                _registered_method=True)
        self.UpdateMetadata = channel.unary_unary(
                '/file_storage.FileStorageService/UpdateMetadata',
                request_serializer=file__storage__pb2.UpdateMetadataRequest.SerializeToString,
                response_deserializer=file__storage__pb2.UpdateMetadataResponse.FromString,
                _registered_method=True)
        self.GeneratePresignedURL = channel.unary_unary(
                '/file_storage.FileStorageService/GeneratePresignedURL',
                request_serializer=file__storage__pb2.GeneratePresignedURLRequest.SerializeToString,
                response_deserializer=file__storage__pb2.GeneratePresignedURLResponse.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/file_storage.FileStorageService/GetHealth',
                request_serializer=file__storage__pb2.HealthRequest.SerializeToString,
                response_deserializer=file__storage__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.UploadConversationFile = channel.stream_unary(
                '/file_storage.FileStorageService/UploadConversationFile',
                request_serializer=file__storage__pb2.ConversationFileUploadRequest.SerializeToString,
                response_deserializer=file__storage__pb2.ConversationFileUploadResponse.FromString,
                _registered_method=True)
        self.GetConversationFiles = channel.unary_unary(
                '/file_storage.FileStorageService/GetConversationFiles',
                request_serializer=file__storage__pb2.GetConversationFilesRequest.SerializeToString,
                response_deserializer=file__storage__pb2.GetConversationFilesResponse.FromString,
                _registered_method=True)
        self.DownloadConversationFile = channel.unary_stream(
                '/file_storage.FileStorageService/DownloadConversationFile',
                request_serializer=file__storage__pb2.DownloadConversationFileRequest.SerializeToString,
                response_deserializer=file__storage__pb2.DownloadResponse.FromString,
                _registered_method=True)
        self.ValidateFile = channel.unary_unary(
                '/file_storage.FileStorageService/ValidateFile',
                request_serializer=file__storage__pb2.ValidateFileRequest.SerializeToString,
                response_deserializer=file__storage__pb2.ValidateFileResponse.FromString,
                _registered_method=True)


class FileStorageServiceServicer(object):
    """FileStorageService provides file storage operations
    """

    def Upload(self, request_iterator, context):
        """Upload uploads a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Download(self, request, context):
        """Download downloads a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete deletes a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exists(self, request, context):
        """Exists checks if a file exists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """List lists files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadata(self, request, context):
        """GetMetadata gets file metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMetadata(self, request, context):
        """UpdateMetadata updates file metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeneratePresignedURL(self, request, context):
        """GeneratePresignedURL generates a presigned URL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """GetHealth checks service health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadConversationFile(self, request_iterator, context):
        """=== 新增：会话和对话文件管理 ===

        UploadConversationFile uploads a file for a specific conversation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversationFiles(self, request, context):
        """GetConversationFiles gets all files for a conversation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadConversationFile(self, request, context):
        """DownloadConversationFile downloads a file from a conversation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateFile(self, request, context):
        """ValidateFile validates a file (TODO: implement validation logic)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=file__storage__pb2.UploadRequest.FromString,
                    response_serializer=file__storage__pb2.UploadResponse.SerializeToString,
            ),
            'Download': grpc.unary_stream_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=file__storage__pb2.DownloadRequest.FromString,
                    response_serializer=file__storage__pb2.DownloadResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=file__storage__pb2.DeleteRequest.FromString,
                    response_serializer=file__storage__pb2.DeleteResponse.SerializeToString,
            ),
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=file__storage__pb2.ExistsRequest.FromString,
                    response_serializer=file__storage__pb2.ExistsResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=file__storage__pb2.ListRequest.FromString,
                    response_serializer=file__storage__pb2.ListResponse.SerializeToString,
            ),
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=file__storage__pb2.GetMetadataRequest.FromString,
                    response_serializer=file__storage__pb2.GetMetadataResponse.SerializeToString,
            ),
            'UpdateMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMetadata,
                    request_deserializer=file__storage__pb2.UpdateMetadataRequest.FromString,
                    response_serializer=file__storage__pb2.UpdateMetadataResponse.SerializeToString,
            ),
            'GeneratePresignedURL': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePresignedURL,
                    request_deserializer=file__storage__pb2.GeneratePresignedURLRequest.FromString,
                    response_serializer=file__storage__pb2.GeneratePresignedURLResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=file__storage__pb2.HealthRequest.FromString,
                    response_serializer=file__storage__pb2.HealthResponse.SerializeToString,
            ),
            'UploadConversationFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadConversationFile,
                    request_deserializer=file__storage__pb2.ConversationFileUploadRequest.FromString,
                    response_serializer=file__storage__pb2.ConversationFileUploadResponse.SerializeToString,
            ),
            'GetConversationFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversationFiles,
                    request_deserializer=file__storage__pb2.GetConversationFilesRequest.FromString,
                    response_serializer=file__storage__pb2.GetConversationFilesResponse.SerializeToString,
            ),
            'DownloadConversationFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadConversationFile,
                    request_deserializer=file__storage__pb2.DownloadConversationFileRequest.FromString,
                    response_serializer=file__storage__pb2.DownloadResponse.SerializeToString,
            ),
            'ValidateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateFile,
                    request_deserializer=file__storage__pb2.ValidateFileRequest.FromString,
                    response_serializer=file__storage__pb2.ValidateFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'file_storage.FileStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('file_storage.FileStorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileStorageService(object):
    """FileStorageService provides file storage operations
    """

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/file_storage.FileStorageService/Upload',
            file__storage__pb2.UploadRequest.SerializeToString,
            file__storage__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/file_storage.FileStorageService/Download',
            file__storage__pb2.DownloadRequest.SerializeToString,
            file__storage__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_storage.FileStorageService/Delete',
            file__storage__pb2.DeleteRequest.SerializeToString,
            file__storage__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_storage.FileStorageService/Exists',
            file__storage__pb2.ExistsRequest.SerializeToString,
            file__storage__pb2.ExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_storage.FileStorageService/List',
            file__storage__pb2.ListRequest.SerializeToString,
            file__storage__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_storage.FileStorageService/GetMetadata',
            file__storage__pb2.GetMetadataRequest.SerializeToString,
            file__storage__pb2.GetMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_storage.FileStorageService/UpdateMetadata',
            file__storage__pb2.UpdateMetadataRequest.SerializeToString,
            file__storage__pb2.UpdateMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeneratePresignedURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_storage.FileStorageService/GeneratePresignedURL',
            file__storage__pb2.GeneratePresignedURLRequest.SerializeToString,
            file__storage__pb2.GeneratePresignedURLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_storage.FileStorageService/GetHealth',
            file__storage__pb2.HealthRequest.SerializeToString,
            file__storage__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadConversationFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/file_storage.FileStorageService/UploadConversationFile',
            file__storage__pb2.ConversationFileUploadRequest.SerializeToString,
            file__storage__pb2.ConversationFileUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversationFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_storage.FileStorageService/GetConversationFiles',
            file__storage__pb2.GetConversationFilesRequest.SerializeToString,
            file__storage__pb2.GetConversationFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadConversationFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/file_storage.FileStorageService/DownloadConversationFile',
            file__storage__pb2.DownloadConversationFileRequest.SerializeToString,
            file__storage__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_storage.FileStorageService/ValidateFile',
            file__storage__pb2.ValidateFileRequest.SerializeToString,
            file__storage__pb2.ValidateFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
