# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import kardcraft_pb2 as kardcraft__pb2


class TaskOrchestratorStub(object):
    """============================================================================
    任务编排服务 (Go -> Python)
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/kardcraft.TaskOrchestrator/CreateTask',
                request_serializer=kardcraft__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.GetTaskStatus = channel.unary_unary(
                '/kardcraft.TaskOrchestrator/GetTaskStatus',
                request_serializer=kardcraft__pb2.TaskStatusRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.TaskStatusResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/kardcraft.TaskOrchestrator/CancelTask',
                request_serializer=kardcraft__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/kardcraft.TaskOrchestrator/ListTasks',
                request_serializer=kardcraft__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.StreamTaskProgress = channel.unary_stream(
                '/kardcraft.TaskOrchestrator/StreamTaskProgress',
                request_serializer=kardcraft__pb2.TaskProgressRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.TaskProgressResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/kardcraft.TaskOrchestrator/HealthCheck',
                request_serializer=kardcraft__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class TaskOrchestratorServicer(object):
    """============================================================================
    任务编排服务 (Go -> Python)
    ============================================================================

    """

    def CreateTask(self, request, context):
        """创建任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """获取任务状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """取消任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """列出用户任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTaskProgress(self, request, context):
        """流式任务进度
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=kardcraft__pb2.CreateTaskRequest.FromString,
                    response_serializer=kardcraft__pb2.TaskResponse.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=kardcraft__pb2.TaskStatusRequest.FromString,
                    response_serializer=kardcraft__pb2.TaskStatusResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=kardcraft__pb2.CancelTaskRequest.FromString,
                    response_serializer=kardcraft__pb2.CancelTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=kardcraft__pb2.ListTasksRequest.FromString,
                    response_serializer=kardcraft__pb2.ListTasksResponse.SerializeToString,
            ),
            'StreamTaskProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTaskProgress,
                    request_deserializer=kardcraft__pb2.TaskProgressRequest.FromString,
                    response_serializer=kardcraft__pb2.TaskProgressResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=kardcraft__pb2.HealthCheckRequest.FromString,
                    response_serializer=kardcraft__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kardcraft.TaskOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kardcraft.TaskOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskOrchestrator(object):
    """============================================================================
    任务编排服务 (Go -> Python)
    ============================================================================

    """

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.TaskOrchestrator/CreateTask',
            kardcraft__pb2.CreateTaskRequest.SerializeToString,
            kardcraft__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.TaskOrchestrator/GetTaskStatus',
            kardcraft__pb2.TaskStatusRequest.SerializeToString,
            kardcraft__pb2.TaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.TaskOrchestrator/CancelTask',
            kardcraft__pb2.CancelTaskRequest.SerializeToString,
            kardcraft__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.TaskOrchestrator/ListTasks',
            kardcraft__pb2.ListTasksRequest.SerializeToString,
            kardcraft__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTaskProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kardcraft.TaskOrchestrator/StreamTaskProgress',
            kardcraft__pb2.TaskProgressRequest.SerializeToString,
            kardcraft__pb2.TaskProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.TaskOrchestrator/HealthCheck',
            kardcraft__pb2.HealthCheckRequest.SerializeToString,
            kardcraft__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PythonWorkflowStub(object):
    """============================================================================
    Python工作流服务 (Python -> Go/Rust)
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteWorkflow = channel.unary_unary(
                '/kardcraft.PythonWorkflow/ExecuteWorkflow',
                request_serializer=kardcraft__pb2.WorkflowRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.WorkflowResponse.FromString,
                _registered_method=True)
        self.ResumeWorkflow = channel.unary_unary(
                '/kardcraft.PythonWorkflow/ResumeWorkflow',
                request_serializer=kardcraft__pb2.ResumeRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.WorkflowResponse.FromString,
                _registered_method=True)
        self.GetWorkflowStatus = channel.unary_unary(
                '/kardcraft.PythonWorkflow/GetWorkflowStatus',
                request_serializer=kardcraft__pb2.WorkflowStatusRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.WorkflowStatusResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/kardcraft.PythonWorkflow/HealthCheck',
                request_serializer=kardcraft__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PythonWorkflowServicer(object):
    """============================================================================
    Python工作流服务 (Python -> Go/Rust)
    ============================================================================

    """

    def ExecuteWorkflow(self, request, context):
        """执行工作流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeWorkflow(self, request, context):
        """恢复工作流（从Checkpoint）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflowStatus(self, request, context):
        """获取工作流状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PythonWorkflowServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteWorkflow,
                    request_deserializer=kardcraft__pb2.WorkflowRequest.FromString,
                    response_serializer=kardcraft__pb2.WorkflowResponse.SerializeToString,
            ),
            'ResumeWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeWorkflow,
                    request_deserializer=kardcraft__pb2.ResumeRequest.FromString,
                    response_serializer=kardcraft__pb2.WorkflowResponse.SerializeToString,
            ),
            'GetWorkflowStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflowStatus,
                    request_deserializer=kardcraft__pb2.WorkflowStatusRequest.FromString,
                    response_serializer=kardcraft__pb2.WorkflowStatusResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=kardcraft__pb2.HealthCheckRequest.FromString,
                    response_serializer=kardcraft__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kardcraft.PythonWorkflow', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kardcraft.PythonWorkflow', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PythonWorkflow(object):
    """============================================================================
    Python工作流服务 (Python -> Go/Rust)
    ============================================================================

    """

    @staticmethod
    def ExecuteWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.PythonWorkflow/ExecuteWorkflow',
            kardcraft__pb2.WorkflowRequest.SerializeToString,
            kardcraft__pb2.WorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.PythonWorkflow/ResumeWorkflow',
            kardcraft__pb2.ResumeRequest.SerializeToString,
            kardcraft__pb2.WorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflowStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.PythonWorkflow/GetWorkflowStatus',
            kardcraft__pb2.WorkflowStatusRequest.SerializeToString,
            kardcraft__pb2.WorkflowStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.PythonWorkflow/HealthCheck',
            kardcraft__pb2.HealthCheckRequest.SerializeToString,
            kardcraft__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RustServicesStub(object):
    """============================================================================
    Rust高性能服务 (Rust -> Python/Go)
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseDocument = channel.unary_unary(
                '/kardcraft.RustServices/ParseDocument',
                request_serializer=kardcraft__pb2.ParseRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.ParseResponse.FromString,
                _registered_method=True)
        self.BatchParseDocuments = channel.unary_stream(
                '/kardcraft.RustServices/BatchParseDocuments',
                request_serializer=kardcraft__pb2.BatchParseRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.BatchParseResponse.FromString,
                _registered_method=True)
        self.VectorSearch = channel.unary_unary(
                '/kardcraft.RustServices/VectorSearch',
                request_serializer=kardcraft__pb2.VectorSearchRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.VectorSearchResponse.FromString,
                _registered_method=True)
        self.InsertVectors = channel.unary_unary(
                '/kardcraft.RustServices/InsertVectors',
                request_serializer=kardcraft__pb2.InsertVectorsRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.InsertVectorsResponse.FromString,
                _registered_method=True)
        self.SaveFile = channel.unary_unary(
                '/kardcraft.RustServices/SaveFile',
                request_serializer=kardcraft__pb2.SaveFileRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.SaveFileResponse.FromString,
                _registered_method=True)
        self.GetFile = channel.unary_unary(
                '/kardcraft.RustServices/GetFile',
                request_serializer=kardcraft__pb2.GetFileRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.GetFileResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/kardcraft.RustServices/HealthCheck',
                request_serializer=kardcraft__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class RustServicesServicer(object):
    """============================================================================
    Rust高性能服务 (Rust -> Python/Go)
    ============================================================================

    """

    def ParseDocument(self, request, context):
        """文档解析
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchParseDocuments(self, request, context):
        """批量文档解析
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorSearch(self, request, context):
        """向量搜索
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertVectors(self, request, context):
        """插入向量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveFile(self, request, context):
        """文件操作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RustServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseDocument,
                    request_deserializer=kardcraft__pb2.ParseRequest.FromString,
                    response_serializer=kardcraft__pb2.ParseResponse.SerializeToString,
            ),
            'BatchParseDocuments': grpc.unary_stream_rpc_method_handler(
                    servicer.BatchParseDocuments,
                    request_deserializer=kardcraft__pb2.BatchParseRequest.FromString,
                    response_serializer=kardcraft__pb2.BatchParseResponse.SerializeToString,
            ),
            'VectorSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.VectorSearch,
                    request_deserializer=kardcraft__pb2.VectorSearchRequest.FromString,
                    response_serializer=kardcraft__pb2.VectorSearchResponse.SerializeToString,
            ),
            'InsertVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertVectors,
                    request_deserializer=kardcraft__pb2.InsertVectorsRequest.FromString,
                    response_serializer=kardcraft__pb2.InsertVectorsResponse.SerializeToString,
            ),
            'SaveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveFile,
                    request_deserializer=kardcraft__pb2.SaveFileRequest.FromString,
                    response_serializer=kardcraft__pb2.SaveFileResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=kardcraft__pb2.GetFileRequest.FromString,
                    response_serializer=kardcraft__pb2.GetFileResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=kardcraft__pb2.HealthCheckRequest.FromString,
                    response_serializer=kardcraft__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kardcraft.RustServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kardcraft.RustServices', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RustServices(object):
    """============================================================================
    Rust高性能服务 (Rust -> Python/Go)
    ============================================================================

    """

    @staticmethod
    def ParseDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.RustServices/ParseDocument',
            kardcraft__pb2.ParseRequest.SerializeToString,
            kardcraft__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchParseDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kardcraft.RustServices/BatchParseDocuments',
            kardcraft__pb2.BatchParseRequest.SerializeToString,
            kardcraft__pb2.BatchParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VectorSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.RustServices/VectorSearch',
            kardcraft__pb2.VectorSearchRequest.SerializeToString,
            kardcraft__pb2.VectorSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.RustServices/InsertVectors',
            kardcraft__pb2.InsertVectorsRequest.SerializeToString,
            kardcraft__pb2.InsertVectorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.RustServices/SaveFile',
            kardcraft__pb2.SaveFileRequest.SerializeToString,
            kardcraft__pb2.SaveFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.RustServices/GetFile',
            kardcraft__pb2.GetFileRequest.SerializeToString,
            kardcraft__pb2.GetFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.RustServices/HealthCheck',
            kardcraft__pb2.HealthCheckRequest.SerializeToString,
            kardcraft__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EventStreamStub(object):
    """============================================================================
    事件流服务
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeTaskEvents = channel.unary_stream(
                '/kardcraft.EventStream/SubscribeTaskEvents',
                request_serializer=kardcraft__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.Event.FromString,
                _registered_method=True)
        self.PublishEvent = channel.unary_unary(
                '/kardcraft.EventStream/PublishEvent',
                request_serializer=kardcraft__pb2.PublishRequest.SerializeToString,
                response_deserializer=kardcraft__pb2.PublishResponse.FromString,
                _registered_method=True)


class EventStreamServicer(object):
    """============================================================================
    事件流服务
    ============================================================================

    """

    def SubscribeTaskEvents(self, request, context):
        """订阅任务事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishEvent(self, request, context):
        """发布事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeTaskEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTaskEvents,
                    request_deserializer=kardcraft__pb2.SubscribeRequest.FromString,
                    response_serializer=kardcraft__pb2.Event.SerializeToString,
            ),
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=kardcraft__pb2.PublishRequest.FromString,
                    response_serializer=kardcraft__pb2.PublishResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kardcraft.EventStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kardcraft.EventStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventStream(object):
    """============================================================================
    事件流服务
    ============================================================================

    """

    @staticmethod
    def SubscribeTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kardcraft.EventStream/SubscribeTaskEvents',
            kardcraft__pb2.SubscribeRequest.SerializeToString,
            kardcraft__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kardcraft.EventStream/PublishEvent',
            kardcraft__pb2.PublishRequest.SerializeToString,
            kardcraft__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
