# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import sandbox_broker_pb2 as sandbox__broker__pb2


class SandboxBrokerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/sandboxbroker.v1.SandboxBrokerService/Execute',
                request_serializer=sandbox__broker__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=sandbox__broker__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/sandboxbroker.v1.SandboxBrokerService/Start',
                request_serializer=sandbox__broker__pb2.StartRequest.SerializeToString,
                response_deserializer=sandbox__broker__pb2.ExecutionProgress.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/sandboxbroker.v1.SandboxBrokerService/Resume',
                request_serializer=sandbox__broker__pb2.ResumeRequest.SerializeToString,
                response_deserializer=sandbox__broker__pb2.ExecutionProgress.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/sandboxbroker.v1.SandboxBrokerService/GetStatus',
                request_serializer=sandbox__broker__pb2.StatusRequest.SerializeToString,
                response_deserializer=sandbox__broker__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/sandboxbroker.v1.SandboxBrokerService/Cancel',
                request_serializer=sandbox__broker__pb2.CancelRequest.SerializeToString,
                response_deserializer=sandbox__broker__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/sandboxbroker.v1.SandboxBrokerService/Health',
                request_serializer=sandbox__broker__pb2.HealthRequest.SerializeToString,
                response_deserializer=sandbox__broker__pb2.HealthResponse.FromString,
                _registered_method=True)


class SandboxBrokerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxBrokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=sandbox__broker__pb2.ExecuteRequest.FromString,
                    response_serializer=sandbox__broker__pb2.ExecuteResponse.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=sandbox__broker__pb2.StartRequest.FromString,
                    response_serializer=sandbox__broker__pb2.ExecutionProgress.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=sandbox__broker__pb2.ResumeRequest.FromString,
                    response_serializer=sandbox__broker__pb2.ExecutionProgress.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=sandbox__broker__pb2.StatusRequest.FromString,
                    response_serializer=sandbox__broker__pb2.StatusResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=sandbox__broker__pb2.CancelRequest.FromString,
                    response_serializer=sandbox__broker__pb2.CancelResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=sandbox__broker__pb2.HealthRequest.FromString,
                    response_serializer=sandbox__broker__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sandboxbroker.v1.SandboxBrokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sandboxbroker.v1.SandboxBrokerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxBrokerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandboxbroker.v1.SandboxBrokerService/Execute',
            sandbox__broker__pb2.ExecuteRequest.SerializeToString,
            sandbox__broker__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandboxbroker.v1.SandboxBrokerService/Start',
            sandbox__broker__pb2.StartRequest.SerializeToString,
            sandbox__broker__pb2.ExecutionProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandboxbroker.v1.SandboxBrokerService/Resume',
            sandbox__broker__pb2.ResumeRequest.SerializeToString,
            sandbox__broker__pb2.ExecutionProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandboxbroker.v1.SandboxBrokerService/GetStatus',
            sandbox__broker__pb2.StatusRequest.SerializeToString,
            sandbox__broker__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandboxbroker.v1.SandboxBrokerService/Cancel',
            sandbox__broker__pb2.CancelRequest.SerializeToString,
            sandbox__broker__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandboxbroker.v1.SandboxBrokerService/Health',
            sandbox__broker__pb2.HealthRequest.SerializeToString,
            sandbox__broker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
