// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: kardcraft.proto

package kardcraftpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskOrchestrator_CreateTask_FullMethodName         = "/kardcraft.TaskOrchestrator/CreateTask"
	TaskOrchestrator_GetTaskStatus_FullMethodName      = "/kardcraft.TaskOrchestrator/GetTaskStatus"
	TaskOrchestrator_CancelTask_FullMethodName         = "/kardcraft.TaskOrchestrator/CancelTask"
	TaskOrchestrator_ListTasks_FullMethodName          = "/kardcraft.TaskOrchestrator/ListTasks"
	TaskOrchestrator_StreamTaskProgress_FullMethodName = "/kardcraft.TaskOrchestrator/StreamTaskProgress"
	TaskOrchestrator_HealthCheck_FullMethodName        = "/kardcraft.TaskOrchestrator/HealthCheck"
)

// TaskOrchestratorClient is the client API for TaskOrchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskOrchestratorClient interface {
	// 创建任务
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// 获取任务状态
	GetTaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error)
	// 取消任务
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
	// 列出用户任务
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// 流式任务进度
	StreamTaskProgress(ctx context.Context, in *TaskProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgressResponse], error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type taskOrchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskOrchestratorClient(cc grpc.ClientConnInterface) TaskOrchestratorClient {
	return &taskOrchestratorClient{cc}
}

func (c *taskOrchestratorClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskOrchestrator_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskOrchestratorClient) GetTaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatusResponse)
	err := c.cc.Invoke(ctx, TaskOrchestrator_GetTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskOrchestratorClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, TaskOrchestrator_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskOrchestratorClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, TaskOrchestrator_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskOrchestratorClient) StreamTaskProgress(ctx context.Context, in *TaskProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgressResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskOrchestrator_ServiceDesc.Streams[0], TaskOrchestrator_StreamTaskProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskProgressRequest, TaskProgressResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskOrchestrator_StreamTaskProgressClient = grpc.ServerStreamingClient[TaskProgressResponse]

func (c *taskOrchestratorClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, TaskOrchestrator_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskOrchestratorServer is the server API for TaskOrchestrator service.
// All implementations must embed UnimplementedTaskOrchestratorServer
// for forward compatibility.
type TaskOrchestratorServer interface {
	// 创建任务
	CreateTask(context.Context, *CreateTaskRequest) (*TaskResponse, error)
	// 获取任务状态
	GetTaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusResponse, error)
	// 取消任务
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	// 列出用户任务
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// 流式任务进度
	StreamTaskProgress(*TaskProgressRequest, grpc.ServerStreamingServer[TaskProgressResponse]) error
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedTaskOrchestratorServer()
}

// UnimplementedTaskOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskOrchestratorServer struct{}

func (UnimplementedTaskOrchestratorServer) CreateTask(context.Context, *CreateTaskRequest) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedTaskOrchestratorServer) GetTaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedTaskOrchestratorServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedTaskOrchestratorServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedTaskOrchestratorServer) StreamTaskProgress(*TaskProgressRequest, grpc.ServerStreamingServer[TaskProgressResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamTaskProgress not implemented")
}
func (UnimplementedTaskOrchestratorServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedTaskOrchestratorServer) mustEmbedUnimplementedTaskOrchestratorServer() {}
func (UnimplementedTaskOrchestratorServer) testEmbeddedByValue()                          {}

// UnsafeTaskOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskOrchestratorServer will
// result in compilation errors.
type UnsafeTaskOrchestratorServer interface {
	mustEmbedUnimplementedTaskOrchestratorServer()
}

func RegisterTaskOrchestratorServer(s grpc.ServiceRegistrar, srv TaskOrchestratorServer) {
	// If the following call panics, it indicates UnimplementedTaskOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskOrchestrator_ServiceDesc, srv)
}

func _TaskOrchestrator_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskOrchestratorServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskOrchestrator_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskOrchestratorServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskOrchestrator_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskOrchestratorServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskOrchestrator_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskOrchestratorServer).GetTaskStatus(ctx, req.(*TaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskOrchestrator_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskOrchestratorServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskOrchestrator_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskOrchestratorServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskOrchestrator_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskOrchestratorServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskOrchestrator_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskOrchestratorServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskOrchestrator_StreamTaskProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskProgressRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskOrchestratorServer).StreamTaskProgress(m, &grpc.GenericServerStream[TaskProgressRequest, TaskProgressResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskOrchestrator_StreamTaskProgressServer = grpc.ServerStreamingServer[TaskProgressResponse]

func _TaskOrchestrator_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskOrchestratorServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskOrchestrator_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskOrchestratorServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskOrchestrator_ServiceDesc is the grpc.ServiceDesc for TaskOrchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskOrchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kardcraft.TaskOrchestrator",
	HandlerType: (*TaskOrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _TaskOrchestrator_CreateTask_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _TaskOrchestrator_GetTaskStatus_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _TaskOrchestrator_CancelTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _TaskOrchestrator_ListTasks_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _TaskOrchestrator_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTaskProgress",
			Handler:       _TaskOrchestrator_StreamTaskProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kardcraft.proto",
}

const (
	PythonWorkflow_ExecuteWorkflow_FullMethodName   = "/kardcraft.PythonWorkflow/ExecuteWorkflow"
	PythonWorkflow_ResumeWorkflow_FullMethodName    = "/kardcraft.PythonWorkflow/ResumeWorkflow"
	PythonWorkflow_GetWorkflowStatus_FullMethodName = "/kardcraft.PythonWorkflow/GetWorkflowStatus"
	PythonWorkflow_HealthCheck_FullMethodName       = "/kardcraft.PythonWorkflow/HealthCheck"
)

// PythonWorkflowClient is the client API for PythonWorkflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PythonWorkflowClient interface {
	// 执行工作流
	ExecuteWorkflow(ctx context.Context, in *WorkflowRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	// 恢复工作流（从Checkpoint）
	ResumeWorkflow(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	// 获取工作流状态
	GetWorkflowStatus(ctx context.Context, in *WorkflowStatusRequest, opts ...grpc.CallOption) (*WorkflowStatusResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type pythonWorkflowClient struct {
	cc grpc.ClientConnInterface
}

func NewPythonWorkflowClient(cc grpc.ClientConnInterface) PythonWorkflowClient {
	return &pythonWorkflowClient{cc}
}

func (c *pythonWorkflowClient) ExecuteWorkflow(ctx context.Context, in *WorkflowRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowResponse)
	err := c.cc.Invoke(ctx, PythonWorkflow_ExecuteWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pythonWorkflowClient) ResumeWorkflow(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowResponse)
	err := c.cc.Invoke(ctx, PythonWorkflow_ResumeWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pythonWorkflowClient) GetWorkflowStatus(ctx context.Context, in *WorkflowStatusRequest, opts ...grpc.CallOption) (*WorkflowStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowStatusResponse)
	err := c.cc.Invoke(ctx, PythonWorkflow_GetWorkflowStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pythonWorkflowClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PythonWorkflow_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PythonWorkflowServer is the server API for PythonWorkflow service.
// All implementations must embed UnimplementedPythonWorkflowServer
// for forward compatibility.
type PythonWorkflowServer interface {
	// 执行工作流
	ExecuteWorkflow(context.Context, *WorkflowRequest) (*WorkflowResponse, error)
	// 恢复工作流（从Checkpoint）
	ResumeWorkflow(context.Context, *ResumeRequest) (*WorkflowResponse, error)
	// 获取工作流状态
	GetWorkflowStatus(context.Context, *WorkflowStatusRequest) (*WorkflowStatusResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedPythonWorkflowServer()
}

// UnimplementedPythonWorkflowServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPythonWorkflowServer struct{}

func (UnimplementedPythonWorkflowServer) ExecuteWorkflow(context.Context, *WorkflowRequest) (*WorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteWorkflow not implemented")
}
func (UnimplementedPythonWorkflowServer) ResumeWorkflow(context.Context, *ResumeRequest) (*WorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeWorkflow not implemented")
}
func (UnimplementedPythonWorkflowServer) GetWorkflowStatus(context.Context, *WorkflowStatusRequest) (*WorkflowStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowStatus not implemented")
}
func (UnimplementedPythonWorkflowServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPythonWorkflowServer) mustEmbedUnimplementedPythonWorkflowServer() {}
func (UnimplementedPythonWorkflowServer) testEmbeddedByValue()                        {}

// UnsafePythonWorkflowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PythonWorkflowServer will
// result in compilation errors.
type UnsafePythonWorkflowServer interface {
	mustEmbedUnimplementedPythonWorkflowServer()
}

func RegisterPythonWorkflowServer(s grpc.ServiceRegistrar, srv PythonWorkflowServer) {
	// If the following call panics, it indicates UnimplementedPythonWorkflowServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PythonWorkflow_ServiceDesc, srv)
}

func _PythonWorkflow_ExecuteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PythonWorkflowServer).ExecuteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PythonWorkflow_ExecuteWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PythonWorkflowServer).ExecuteWorkflow(ctx, req.(*WorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PythonWorkflow_ResumeWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PythonWorkflowServer).ResumeWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PythonWorkflow_ResumeWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PythonWorkflowServer).ResumeWorkflow(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PythonWorkflow_GetWorkflowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PythonWorkflowServer).GetWorkflowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PythonWorkflow_GetWorkflowStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PythonWorkflowServer).GetWorkflowStatus(ctx, req.(*WorkflowStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PythonWorkflow_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PythonWorkflowServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PythonWorkflow_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PythonWorkflowServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PythonWorkflow_ServiceDesc is the grpc.ServiceDesc for PythonWorkflow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PythonWorkflow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kardcraft.PythonWorkflow",
	HandlerType: (*PythonWorkflowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteWorkflow",
			Handler:    _PythonWorkflow_ExecuteWorkflow_Handler,
		},
		{
			MethodName: "ResumeWorkflow",
			Handler:    _PythonWorkflow_ResumeWorkflow_Handler,
		},
		{
			MethodName: "GetWorkflowStatus",
			Handler:    _PythonWorkflow_GetWorkflowStatus_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PythonWorkflow_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kardcraft.proto",
}

const (
	RustServices_ParseDocument_FullMethodName       = "/kardcraft.RustServices/ParseDocument"
	RustServices_BatchParseDocuments_FullMethodName = "/kardcraft.RustServices/BatchParseDocuments"
	RustServices_VectorSearch_FullMethodName        = "/kardcraft.RustServices/VectorSearch"
	RustServices_InsertVectors_FullMethodName       = "/kardcraft.RustServices/InsertVectors"
	RustServices_SaveFile_FullMethodName            = "/kardcraft.RustServices/SaveFile"
	RustServices_GetFile_FullMethodName             = "/kardcraft.RustServices/GetFile"
	RustServices_HealthCheck_FullMethodName         = "/kardcraft.RustServices/HealthCheck"
)

// RustServicesClient is the client API for RustServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RustServicesClient interface {
	// 文档解析
	ParseDocument(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error)
	// 批量文档解析
	BatchParseDocuments(ctx context.Context, in *BatchParseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BatchParseResponse], error)
	// 向量搜索
	VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error)
	// 插入向量
	InsertVectors(ctx context.Context, in *InsertVectorsRequest, opts ...grpc.CallOption) (*InsertVectorsResponse, error)
	// 文件操作
	SaveFile(ctx context.Context, in *SaveFileRequest, opts ...grpc.CallOption) (*SaveFileResponse, error)
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type rustServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewRustServicesClient(cc grpc.ClientConnInterface) RustServicesClient {
	return &rustServicesClient{cc}
}

func (c *rustServicesClient) ParseDocument(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseResponse)
	err := c.cc.Invoke(ctx, RustServices_ParseDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rustServicesClient) BatchParseDocuments(ctx context.Context, in *BatchParseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BatchParseResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RustServices_ServiceDesc.Streams[0], RustServices_BatchParseDocuments_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchParseRequest, BatchParseResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RustServices_BatchParseDocumentsClient = grpc.ServerStreamingClient[BatchParseResponse]

func (c *rustServicesClient) VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorSearchResponse)
	err := c.cc.Invoke(ctx, RustServices_VectorSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rustServicesClient) InsertVectors(ctx context.Context, in *InsertVectorsRequest, opts ...grpc.CallOption) (*InsertVectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertVectorsResponse)
	err := c.cc.Invoke(ctx, RustServices_InsertVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rustServicesClient) SaveFile(ctx context.Context, in *SaveFileRequest, opts ...grpc.CallOption) (*SaveFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveFileResponse)
	err := c.cc.Invoke(ctx, RustServices_SaveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rustServicesClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, RustServices_GetFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rustServicesClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, RustServices_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RustServicesServer is the server API for RustServices service.
// All implementations must embed UnimplementedRustServicesServer
// for forward compatibility.
type RustServicesServer interface {
	// 文档解析
	ParseDocument(context.Context, *ParseRequest) (*ParseResponse, error)
	// 批量文档解析
	BatchParseDocuments(*BatchParseRequest, grpc.ServerStreamingServer[BatchParseResponse]) error
	// 向量搜索
	VectorSearch(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error)
	// 插入向量
	InsertVectors(context.Context, *InsertVectorsRequest) (*InsertVectorsResponse, error)
	// 文件操作
	SaveFile(context.Context, *SaveFileRequest) (*SaveFileResponse, error)
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedRustServicesServer()
}

// UnimplementedRustServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRustServicesServer struct{}

func (UnimplementedRustServicesServer) ParseDocument(context.Context, *ParseRequest) (*ParseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseDocument not implemented")
}
func (UnimplementedRustServicesServer) BatchParseDocuments(*BatchParseRequest, grpc.ServerStreamingServer[BatchParseResponse]) error {
	return status.Error(codes.Unimplemented, "method BatchParseDocuments not implemented")
}
func (UnimplementedRustServicesServer) VectorSearch(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorSearch not implemented")
}
func (UnimplementedRustServicesServer) InsertVectors(context.Context, *InsertVectorsRequest) (*InsertVectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertVectors not implemented")
}
func (UnimplementedRustServicesServer) SaveFile(context.Context, *SaveFileRequest) (*SaveFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveFile not implemented")
}
func (UnimplementedRustServicesServer) GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedRustServicesServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedRustServicesServer) mustEmbedUnimplementedRustServicesServer() {}
func (UnimplementedRustServicesServer) testEmbeddedByValue()                      {}

// UnsafeRustServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RustServicesServer will
// result in compilation errors.
type UnsafeRustServicesServer interface {
	mustEmbedUnimplementedRustServicesServer()
}

func RegisterRustServicesServer(s grpc.ServiceRegistrar, srv RustServicesServer) {
	// If the following call panics, it indicates UnimplementedRustServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RustServices_ServiceDesc, srv)
}

func _RustServices_ParseDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RustServicesServer).ParseDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RustServices_ParseDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RustServicesServer).ParseDocument(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RustServices_BatchParseDocuments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BatchParseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RustServicesServer).BatchParseDocuments(m, &grpc.GenericServerStream[BatchParseRequest, BatchParseResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RustServices_BatchParseDocumentsServer = grpc.ServerStreamingServer[BatchParseResponse]

func _RustServices_VectorSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RustServicesServer).VectorSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RustServices_VectorSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RustServicesServer).VectorSearch(ctx, req.(*VectorSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RustServices_InsertVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertVectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RustServicesServer).InsertVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RustServices_InsertVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RustServicesServer).InsertVectors(ctx, req.(*InsertVectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RustServices_SaveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RustServicesServer).SaveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RustServices_SaveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RustServicesServer).SaveFile(ctx, req.(*SaveFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RustServices_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RustServicesServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RustServices_GetFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RustServicesServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RustServices_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RustServicesServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RustServices_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RustServicesServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RustServices_ServiceDesc is the grpc.ServiceDesc for RustServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RustServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kardcraft.RustServices",
	HandlerType: (*RustServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseDocument",
			Handler:    _RustServices_ParseDocument_Handler,
		},
		{
			MethodName: "VectorSearch",
			Handler:    _RustServices_VectorSearch_Handler,
		},
		{
			MethodName: "InsertVectors",
			Handler:    _RustServices_InsertVectors_Handler,
		},
		{
			MethodName: "SaveFile",
			Handler:    _RustServices_SaveFile_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _RustServices_GetFile_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _RustServices_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BatchParseDocuments",
			Handler:       _RustServices_BatchParseDocuments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kardcraft.proto",
}

const (
	EventStream_SubscribeTaskEvents_FullMethodName = "/kardcraft.EventStream/SubscribeTaskEvents"
	EventStream_PublishEvent_FullMethodName        = "/kardcraft.EventStream/PublishEvent"
)

// EventStreamClient is the client API for EventStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventStreamClient interface {
	// 订阅任务事件
	SubscribeTaskEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// 发布事件
	PublishEvent(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
}

type eventStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewEventStreamClient(cc grpc.ClientConnInterface) EventStreamClient {
	return &eventStreamClient{cc}
}

func (c *eventStreamClient) SubscribeTaskEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStream_ServiceDesc.Streams[0], EventStream_SubscribeTaskEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStream_SubscribeTaskEventsClient = grpc.ServerStreamingClient[Event]

func (c *eventStreamClient) PublishEvent(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, EventStream_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventStreamServer is the server API for EventStream service.
// All implementations must embed UnimplementedEventStreamServer
// for forward compatibility.
type EventStreamServer interface {
	// 订阅任务事件
	SubscribeTaskEvents(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error
	// 发布事件
	PublishEvent(context.Context, *PublishRequest) (*PublishResponse, error)
	mustEmbedUnimplementedEventStreamServer()
}

// UnimplementedEventStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventStreamServer struct{}

func (UnimplementedEventStreamServer) SubscribeTaskEvents(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method SubscribeTaskEvents not implemented")
}
func (UnimplementedEventStreamServer) PublishEvent(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedEventStreamServer) mustEmbedUnimplementedEventStreamServer() {}
func (UnimplementedEventStreamServer) testEmbeddedByValue()                     {}

// UnsafeEventStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventStreamServer will
// result in compilation errors.
type UnsafeEventStreamServer interface {
	mustEmbedUnimplementedEventStreamServer()
}

func RegisterEventStreamServer(s grpc.ServiceRegistrar, srv EventStreamServer) {
	// If the following call panics, it indicates UnimplementedEventStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventStream_ServiceDesc, srv)
}

func _EventStream_SubscribeTaskEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStreamServer).SubscribeTaskEvents(m, &grpc.GenericServerStream[SubscribeRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStream_SubscribeTaskEventsServer = grpc.ServerStreamingServer[Event]

func _EventStream_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStreamServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventStream_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStreamServer).PublishEvent(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventStream_ServiceDesc is the grpc.ServiceDesc for EventStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kardcraft.EventStream",
	HandlerType: (*EventStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishEvent",
			Handler:    _EventStream_PublishEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeTaskEvents",
			Handler:       _EventStream_SubscribeTaskEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kardcraft.proto",
}
